In [4]:
# importing the necessory libraries
import tensorflow as tf

### Tensor
* Tensor is a genrallization of vectors and Matrix

In [11]:
# Zero order tensor
tensor1 = tf.Variable(34, tf.int32)
tensor2 = tf.Variable("Hello", tf.string)
tensor3 = tf.Variable(6.7, tf.float64)

In [13]:
# rank 1 tensor
rank1_tensor = tf.Variable(["Apple"], tf.string)
# rank 2 tensor
rank2_tensor = tf.Variable([[1,2,3,4],[5,6,7,8],[9,10,11,12]], tf.int64)

### Rank/Digree of the tensor
* It simply Means the dimension of the tensor

In [14]:
# Creating a 2nd order tensor
tensor1 = tf.Variable([[1,2,3],[4,5,6]],tf.int64)
print(tf.rank(tensor1))

tf.Tensor(2, shape=(), dtype=int32)


In [16]:
# Creating a Rank 3 tensor
tensor2 = tf.Variable([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(tf.rank(tensor2))

tf.Tensor(3, shape=(), dtype=int32)


### Shape of the tensor
* It gives the discription about the number of elements existing in each diemension.

In [19]:
tensor2 = tf.Variable([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(tensor2.shape)

(2, 2, 3)


### Reshaping the tensor
* This is used to reshape the existing Tensor  

In [23]:
tensor3 = tf.Variable([1,2,3,4,5,6,7,8], tf.int64)
print("tensor3.shape = ",tensor3.shape)
tensor3 = tf.reshape(tensor3, (2,2,2))
print("tensor3.shape = ",tensor3.shape)

tensor3.shape =  (8,)
tensor3.shape =  (2, 2, 2)


### Ones ,Zeros

In [25]:
tensor_zeros = tf.zeros((2,3,4),tf.float64)
tensor_ones = tf.ones((2,5),tf.int64)
print("tensor_zeros= " ,tensor_zeros)
print("Tensor_ones= ", tensor_ones)

tensor_zeros=  tf.Tensor(
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]], shape=(2, 3, 4), dtype=float64)
Tensor_ones=  tf.Tensor(
[[1 1 1 1 1]
 [1 1 1 1 1]], shape=(2, 5), dtype=int64)


### Tensor slicing

In [35]:
# Creating a 2D tensor
tensor = tf.Variable([[2,4,6],[8,10,12]],tf.int64)
print("tensor[0,0] = ",tensor[0,0])
print("tensor[0,2] = ",tensor[0,2])
print("tensor[1,1] = ",tensor[1,1])

tensor[0,0] =  tf.Tensor(2, shape=(), dtype=int32)
tensor[0,2] =  tf.Tensor(6, shape=(), dtype=int32)
tensor[1,1] =  tf.Tensor(10, shape=(), dtype=int32)


In [40]:
# Slicing the tensor of all the rows with 1st column
print("tensor[:,1:2] = ", tensor[:,1:2])

tensor[:,1:2] =  tf.Tensor(
[[ 4]
 [10]], shape=(2, 1), dtype=int32)


In [46]:
# Scling the first row and 1nd and 2nd column
tensor[0:1,1:]

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[4, 6]], dtype=int32)>